### ISSUE TITLE
Unable to install on WSL

### ISSUE THREAD

**Issue by GitHub-user-2020** [nushell/nushell#2999]
I tried installing nushell via Cargo on WSL, but failed to do so.

1. Install the required dependencies on the website.
2. Install nushell via Cargo.

**Expected behavior**
I expected a successful installation of nushell. However, I get the following error:
```bash
error[E0658]: use of unstable library feature 'matches_macro'
  --> /home/[system]/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-json-0.26.0/src/de.rs:74:9
   |
74 |         matches!(ch, b'{' | b'}' | b'[' | b']' | b',' | b':')
   |         ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /home/[system]/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-json-0.26.0/src/value.rs:216:9
    |
216 |         matches!(*self, Value::I64(_) | Value::U64(_) | Value::F64(_))
    |         ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /home/[system]/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-json-0.26.0/src/value.rs:221:9
    |
221 |         matches!(*self, Value::I64(_))
    |         ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /home/[system]/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-json-0.26.0/src/value.rs:226:9
    |
226 |         matches!(*self, Value::U64(_))
    |         ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /home/[system]/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-json-0.26.0/src/value.rs:231:9
    |
231 |         matches!(*self, Value::F64(_))
    |         ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

   Compiling eml-parser v0.1.0
error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `nu-json`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.26.0`, intermediate artifacts can be found at `/tmp/cargo-installqWCqBB`

Caused by:
  build failed
```

**Configuration (please complete the following information):**

Copied from `neofetch --off`, please let me know if there's anything else you need to know about my system config:

```bash
OS: Debian GNU/Linux 10 (buster) on Windows 10 x86_64
Kernel: 4.4.0-18362-Microsoft
Uptime: 30 mins
Packages: 769 (dpkg)
Shell: bash 5.0.3
Terminal: /dev/tty2
CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8) @ 2.300GHz
Memory: 12308MiB / 15807MiB
```

**Comment by jonathandturner** [comment]
Can you check that your version of the Rust compiler is recent enough?

If you do `rustc --version` you should see 1.49.0. It may also build with 1.48.0, I'm not sure, but I suspect earlier versions may have issues.

**Comment by GitHub-user-2020** [comment]
> Can you check that your version of the Rust compiler is recent enough?
> 
> If you do `rustc --version` you should see 1.49.0. It may also build with 1.48.0, I'm not sure, but I suspect earlier versions may have issues.

My current version is 1.41.1, I'll see if upgrading it will fix it.

**Comment by GitHub-user-2020** [comment]
It works. Thanks for this, you can close my issue.
