### ISSUE TITLE
Compilation error zstd-sys

### ISSUE THREAD

**Issue by DeadMozay** [nushell/nushell#3772]
**Describe the bug**
Error appears when compiling zstd-sys

```
[   84s]   --- stderr
[   84s]   thread 'main' panicked at 'Folder 'zstd/lib' does not exists. Maybe you forgot to clone the 'zstd' submodule?', /home/abuild/rpmbuild/BUILD/nushell-0.34.0+1/vendor/zstd-sys/build.rs:180:13
[   84s]   stack backtrace:
[   84s]      0: std::panicking::begin_panic
[   84s]      1: build_script_build::main
[   84s]      2: core::ops::function::FnOnce::call_once
[   84s]   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[   84s] warning: build failed, waiting for other jobs to finish...
[   89s] error: build failed
```

Maybe this is caused by https://github.com/rust-lang/cargo/pull/8095. The filter check for directories doesn't handle the case where there is a ! exclusion.

for zstd-rs a patch has already been adopted and a new release has been released https://github.com/gyscos/zstd-rs/pull/123/commits/add97e3d4f5ec26de71606fbb6cfe9056c98e46f

```
> version | pivot
╭───┬────────────────────┬───────────────────────────────────────────────────────────────────────╮
│ # │ Column0            │ Column1                                                               │
├───┼────────────────────┼───────────────────────────────────────────────────────────────────────┤
│ 0 │ version            │ 0.34.0                                                                │
│ 1 │ build_os           │ openSUSE Tumbleweed                                                          │
│ 2 │ rust_version       │ rustc 1.53.0                                                          │
│ 3 │ cargo_version      │ cargo 1.53.0                                                          │
│ 4 │ pkg_version        │ 0.34.0                                                                │
│ 5 │ build_rust_channel │ release                                                               │
╰───┴────────────────────┴───────────────────────────────────────────────────────────────────────╯
```

**Add any other context about the problem here.**

**Comment by fdncred** [comment]
Are you saying that if you compile this, while running in nushell, it fails to compile?  I just tried in Windows and got this.

```
~/source/repos/forks()                                                                               227|08:31:00.318 AM
└─ $ ▶ git clone https://github.com/gyscos/zstd-rs --recursive
Cloning into 'zstd-rs'...
remote: Enumerating objects: 2191, done.
remote: Counting objects: 100% (450/450), done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 2191 (delta 273), reused 285 (delta 150), pack-reused 1741
Receiving objects: 100% (2191/2191), 587.30 KiB | 1.09 MiB/s, done.
Resolving deltas: 100% (1367/1367), done.
Submodule 'zstd-safe/zstd-sys/zstd' (https://github.com/facebook/zstd) registered for path 'zstd-safe/zstd-sys/zstd'
Cloning into 'C:/Users/dschroeder/source/repos/forks/zstd-rs/zstd-safe/zstd-sys/zstd'...
remote: Enumerating objects: 50285, done.
remote: Counting objects: 100% (1721/1721), done.
remote: Compressing objects: 100% (796/796), done.
remote: Total 50285 (delta 1095), reused 1429 (delta 897), pack-reused 48564
Receiving objects: 100% (50285/50285), 27.91 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (36953/36953), done.
Submodule path 'zstd-safe/zstd-sys/zstd': checked out 'a488ba114ec17ea1054b9057c26a046fc122b3b6'

~/source/repos/forks()                                                                                33|08:32:00.664 AM
└─ $ ▶ cd .\zstd-rs\

~/source/repos/forks/zstd-rs(master)                                                                   0|08:32:07.174 AM
└─ $ ▶ git submodule update --init

~/source/repos/forks/zstd-rs(master)                                                                1902|08:32:11.537 AM
└─ $ ▶ cargo b
    Updating crates.io index
   Compiling zstd-safe v4.1.1+zstd.1.5.0 (C:\Users\dschroeder\source\repos\forks\zstd-rs\zstd-safe)
   Compiling zstd-sys v1.6.1+zstd.1.5.0 (C:\Users\dschroeder\source\repos\forks\zstd-rs\zstd-safe\zstd-sys)
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
   Compiling zstd v0.9.0+zstd.1.5.0 (C:\Users\dschroeder\source\repos\forks\zstd-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 38.36s
```

**Comment by DeadMozay** [comment]
> Are you saying that if you compile this, while running in nushell, it fails to compile? I just tried in Windows and got this.
> 
> ```
> ~/source/repos/forks()                                                                               227|08:31:00.318 AM
> └─ $ ▶ git clone https://github.com/gyscos/zstd-rs --recursive
> Cloning into 'zstd-rs'...
> remote: Enumerating objects: 2191, done.
> remote: Counting objects: 100% (450/450), done.
> remote: Compressing objects: 100% (293/293), done.
> remote: Total 2191 (delta 273), reused 285 (delta 150), pack-reused 1741
> Receiving objects: 100% (2191/2191), 587.30 KiB | 1.09 MiB/s, done.
> Resolving deltas: 100% (1367/1367), done.
> Submodule 'zstd-safe/zstd-sys/zstd' (https://github.com/facebook/zstd) registered for path 'zstd-safe/zstd-sys/zstd'
> Cloning into 'C:/Users/dschroeder/source/repos/forks/zstd-rs/zstd-safe/zstd-sys/zstd'...
> remote: Enumerating objects: 50285, done.
> remote: Counting objects: 100% (1721/1721), done.
> remote: Compressing objects: 100% (796/796), done.
> remote: Total 50285 (delta 1095), reused 1429 (delta 897), pack-reused 48564
> Receiving objects: 100% (50285/50285), 27.91 MiB | 1.24 MiB/s, done.
> Resolving deltas: 100% (36953/36953), done.
> Submodule path 'zstd-safe/zstd-sys/zstd': checked out 'a488ba114ec17ea1054b9057c26a046fc122b3b6'
> 
> ~/source/repos/forks()                                                                                33|08:32:00.664 AM
> └─ $ ▶ cd .\zstd-rs\
> 
> ~/source/repos/forks/zstd-rs(master)                                                                   0|08:32:07.174 AM
> └─ $ ▶ git submodule update --init
> 
> ~/source/repos/forks/zstd-rs(master)                                                                1902|08:32:11.537 AM
> └─ $ ▶ cargo b
>     Updating crates.io index
>    Compiling zstd-safe v4.1.1+zstd.1.5.0 (C:\Users\dschroeder\source\repos\forks\zstd-rs\zstd-safe)
>    Compiling zstd-sys v1.6.1+zstd.1.5.0 (C:\Users\dschroeder\source\repos\forks\zstd-rs\zstd-safe\zstd-sys)
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
> warning: cl : Command line warning D9002 : ignoring unknown option '-fvisibility=hidden'
>    Compiling zstd v0.9.0+zstd.1.5.0 (C:\Users\dschroeder\source\repos\forks\zstd-rs)
>     Finished dev [unoptimized + debuginfo] target(s) in 38.36s
> ```

I have not tried to compile zstd-rs separately, but you already compile the fixed version 0.9.0, nushell from Cargo.toml downloads version 0.8.3 where there is no patch yet

**Comment by fdncred** [comment]
oh, you mean that `zstd-rs` fails when you compile nushell. I didn't understand that. I've compiled nushell a few times this morning without issue. I wonder what is going on.

**Comment by DeadMozay** [comment]
> oh, you mean that `zstd-rs` fails when you compile nushell. I didn't understand that. I've compiled nushell a few times this morning without issue. I wonder what is going on.

You may have older versions of cargo and rust, not 1.53.0

**Comment by fdncred** [comment]
Good point. I was running `rustc 1.52.1`. I'll update and try to compile again.

**Comment by fdncred** [comment]
ok, I updated rust. Then did a `cargo clean`, then did a `cargo build --release --features=extra` and it all built fine.

**Comment by DeadMozay** [comment]
Compiled with `RUST_BACKTRACE=full` and `-v`
[build.log](https://github.com/nushell/nushell/files/6820664/build.log)
Perhaps this will help you understand what is the cause of the error.

**Comment by fdncred** [comment]
I bet the problem is that compiling zstd-sys is a little different since it has submodules. There's a recursive git, which I don't see in the log, then there's a submodule init, which I also don't see in the log. I don't use linux much but I'd bet that you'd have better luck if you just clone the repo and compile nushell yourself. We talk about how to do this in 'the book' here. https://www.nushell.sh/book/installation.html

**Comment by DeadMozay** [comment]
> I bet the problem is that compiling zstd-sys is a little different since it has submodules. There's a recursive git, which I don't see in the log, then there's a submodule init, which I also don't see in the log. I don't use linux much but I'd bet that you'd have better luck if you just clone the repo and compile nushell yourself. We talk about how to do this in 'the book' here. https://www.nushell.sh/book/installation.html

Solved the problem in a different way, zstd-sys only wants to compile with the static library zstd ignoring the system library zstd, when I fixed it, the build succeeded

**Comment by fdncred** [comment]
nice, thanks for the update. if you have time, it may be useful to other folks to know exactly what you did, in case this happens for them. for now though, i'm closing.

**Comment by Br1ght0ne** [comment]
Hi, I'm seeing this issue while trying to upgrade Nushell to 0.34.0 for Nixpkgs ([PR](https://github.com/NixOS/nixpkgs/pull/130760)). `zstd-rs` has an optional feature `pkg-config` that supports using a system-provided `libzstd` (required for Nix(OS) packages, as we can't fetch `zstd` submodule in sandboxed build). I also know that `zstd-rs` is a non-direct dependency (because of `polars -> parquet -> zstd-rs`).

Any way we can set this flag either in Nushell's `Cargo.toml` files, or when running `cargo build`? I'd prefer to refrain from hot-patching `Cargo.lock` files :)

Sorry if it's the wrong place. I'll open an issue in Nixpkgs too.

**Comment by fdncred** [comment]
@Br1ght0ne if you have a suggestion of changing our Cargo.toml to make this easier, please let us know.

**Comment by Br1ght0ne** [comment]
@fdncred Propagating `pkg-config` all the way from `nu-*` to `zstd` (through `polars` and `parquet`) sounds hard to accomplish. I'm researching other methods.
