### ISSUE TITLE
0.111.0 release fails to build on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#17695]
Unfortunately, 0.111.0 fails to build on NetBSD (0.110.0 builds just fine) with

```
error[E0609]: no field `st_atime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:482:23
    |
482 |             self.stat.st_atime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
482 -             self.stat.st_atime_nsec
482 +             self.stat.st_atimensec
    |

error[E0609]: no field `st_mtime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:504:23
    |
504 |             self.stat.st_mtime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
504 -             self.stat.st_mtime_nsec
504 +             self.stat.st_mtimensec
    |

error[E0609]: no field `st_ctime_nsec` on type `FileStat`
   --> /usr/pkgsrc/wip/nushell/work/vendor/uucore-0.6.0/src/lib/features/safe_traversal.rs:526:23
    |
526 |             self.stat.st_ctime_nsec
    |                       ^^^^^^^^^^^^^ unknown field
    |
help: a field with a similar name exists
    |
526 -             self.stat.st_ctime_nsec
526 +             self.stat.st_ctimensec
    |
```

**Comment by fdncred** [comment]
Looks like a upstream problem with uutils. Is there an issue over there already?

**Comment by 0323pin** [comment]
> Looks like a upstream problem with uutils. Is there an issue over there already?

Yes, it does.
```
~> grep -r "st_atime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_mtime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_ctime_nsec" libc-0.2.178/src/unix/bsd/netbsdlike/netbsd
Exception: grep exited with 1
~> grep -r "st_atimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_atimensec: c_long,
~> grep -r "st_mtimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_mtimensec: c_long,
~> grep -r "st_ctimensec" libc-0.2.178//src/unix/bsd/netbsdlike/netbsd
libc-0.2.178/src/unix/bsd/netbsdlike/netbsd/mod.rs:        pub st_ctimensec: c_long,
```

 I'll have a look and if there's none, I'll open one.

BTW, the same is valid for the latest `libc` crate v0.2.182.

**Comment by 0323pin** [comment]
@fdncred closing this now. Hopefully at some point https://github.com/uutils/coreutils/pull/11176 will succeed.

**Comment by fdncred** [comment]
Hopefully it'll get in for their next release.

**Comment by 0323pin** [comment]
> Hopefully it'll get in for their next release.

I've patched it locally for now and pushed the v0.111.0 update into the main pkgsrc branch, https://mail-index.netbsd.org/pkgsrc-changes/2026/03/02/msg341688.html

**Comment by 0323pin** [comment]
Just FYI, I've pushed 5 commits to uutils/coreutils and git-HEAD now has full support for NetBSD, including CI checks so, this shouldn't happen again in the future.

**Comment by amandalewis1231-lgtm** [comment]
Thank you for the update.
