### PR TITLE
Put heavy dataframe dependencies behind feature flag

### PR DESCRIPTION
**Pull request by rgwood**
Context from Discord: https://discord.com/channels/601130461678272522/615962413203718156/1138694933545504819

I was working on Nu for the first time in a while and I noticed that sometimes rust-analyzer takes a really long time to run `cargo check` on the entire workspace. I dug in and it was checking a bunch of dataframe-related dependencies even though the `dataframe` feature is not built by default.

It looks like this is a regression of sorts, introduced by https://github.com/nushell/nushell/pull/9241. Thankfully the fix is pretty easy, we can make it so everything important in `nu-cmd-dataframe` is only used when the `dataframe` feature is enabled.

### Impact on `cargo check --workspace`

Before this PR: 635 crates, 33.59s
After this PR: 498 crates, ~20s

(with the `mold` linker and a `cargo clean` before each run, the relative difference for incremental checks will likely be much larger)

### CODE REVIEW

**Review by sholderbach — APPROVED** [review]
This will make operations like `cargo test -p nu-cmd-dataframe` a bit surprising, but I think it is overall a good thing for the project.

**Comment by fdncred** [comment]
I'm having a hard time compiling with dataframes now.
```
cargo install --path . --features=dataframe,extra,mimalloc 
  Installing nu v0.83.2 (/Users/fdncred/src/nushell)
    Updating git repository `https://github.com/nushell/reedline.git`
    Updating crates.io index
   Compiling nu v0.83.2 (/Users/fdncred/src/nushell)
error[E0425]: cannot find function `add_dataframe_context` in crate `nu_cmd_dataframe`
  --> src/main.rs:45:42
   |
45 |     let engine_state = nu_cmd_dataframe::add_dataframe_context(engine_state);
   |                                          ^^^^^^^^^^^^^^^^^^^^^ not found in `nu_cmd_dataframe`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `nu` due to previous error
error: failed to compile `nu v0.83.2 (/Users/fdncred/src/nushell)`, intermediate artifacts can be found at `/Users/fdncred/src/nushell/target`
```

**Comment by fdncred** [comment]
Stefan figured it out https://github.com/nushell/nushell/pull/9974

**Comment by rgwood** [comment]
Oops, thanks Stefan!
