### ISSUE TITLE
crate is indistinguishable from one of its dependencies

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#9546]
### Describe the bug

Can not compile 0.82.0 due to crate being indistinguishable from one of its dependencies.

```
error[E0519]: the current crate is indistinguishable from one of its dependencies: it has the same crate-name `generic_array` and was compiled with the same `-C metadata` arguments. This will result in symbol conflicts between the two.
  --> /usr/pkgsrc/wip/nushell/work/vendor/crypto-common-0.1.6/src/lib.rs:18:9
   |
18 | pub use generic_array;
   |         ^^^^^^^^^^^^^

error[E0519]: the current crate is indistinguishable from one of its dependencies: it has the same crate-name `generic_array` and was compiled with the same `-C metadata` arguments. This will result in symbol conflicts between the two.
  --> /usr/pkgsrc/wip/nushell/work/vendor/crypto-common-0.1.6/src/lib.rs:19:9
   |
19 | pub use generic_array::typenum;
   |         ^^^^^^^^^^^^^

error[E0519]: the current crate is indistinguishable from one of its dependencies: it has the same crate-name `generic_array` and was compiled with the same `-C metadata` arguments. This will result in symbol conflicts between the two.
  --> /usr/pkgsrc/wip/nushell/work/vendor/crypto-common-0.1.6/src/lib.rs:22:5
   |
22 | use generic_array::{typenum::Unsigned, ArrayLength, GenericArray};
   |     ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0519`.
error: could not compile `crypto-common` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
*** Error code 101

Stop.
```

### How to reproduce

Build `nu` from source.

### Expected behavior

Build successfully.

### Configuration

See Additional context.

### Additional context

`uname -v`: NetBSD 10.99.4 (GENERIC) #0: Sat Jun 24 17:50:31 UTC 2023
`pkg_info | grep rust`: rust-1.70.0

Build features: `plugin`, `which-support` and `sqlite`

**Comment by 0323pin** [comment]
A bit more info ...
0.82.0 builds fine with Rust-1.69.0 and I've also built 0.81.0 with Rust-1.70.0.
AFAIK, I can see the dependency on `crypto-common`-0.1.6 hasn't changed from 0.81.0 to 0.82.0

So, honestly I don't know why this is happening.
Any hints?

**Comment by 0323pin** [comment]
I kicked another build of 0.82.0 with Rust-1.70.0 on a clean build directory and it worked. Sorry for the noise :(
