### PR TITLE
Make Semicolon stop on error, so it behaves like `&&` in bash

### LINKED ISSUE #6022: Semicolon doesn't stop on error with `cmake` or `make`
### Describe the bug

With `cmake` or `make`  `and  a `semicolon` doesn't understand the error and continues.

```
test/build on  master [!+?] via △ v3.20.5 on ☁️   
❯ make all ; echo done 
Consolidate compiler generated dependencies of target test.x
[ 50%] Building CXX object CMakeFiles/test.x.dir/test.cpp.o
/tmp/test/test.cpp: In function ‘int main(int, char**)’:
/tmp/test/test.cpp:3:3: error: invalid use of ‘this’ in non-member function
    3 |   this is an error
      |   ^~~~
make[2]: *** [CMakeFiles/test.x.dir/build.make:76: CMakeFiles/test.x.dir/test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.x.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
done
```

### How to reproduce

`CMakeLists.txt`:
```  cmake
project(test LANGUAGES CXX)
cmake_minimum_required(VERSION 3.18)

add_executable(test.x test.cpp)
```

`test.cpp`

``` cpp
int main(int argc, char *argv[])
{
  this is an error 
  return 0;
}
```

```
cmake -H. -Bbuild
cmake --build build --target all;echo done
/tmp/test/test.cpp: In function ‘int main(int, char**)’:
/tmp/test/test.cpp:3:3: error: invalid use of ‘this’ in non-member function
    3 |   this is an error
      |   ^~~~
gmake[2]: *** [CMakeFiles/test.x.dir/build.make:76: CMakeFiles/test.x.dir/test.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/test.x.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
done    
```

### Expected behavior

Shouldn't reach the `done` 

### Screenshots

_No response_

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.65.0                              |
| branch             | master                              |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08) |
| pkg_version        | 0.65.0                              |
| build_time         | 2022-07-12 15:42:33 +03:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WindSoilder**
# Description

Fixes #6022, for the following command:
```
^ls asdfasd ; echo done
```
if `^ls asdfasd` failed, `echo done` will never executed again.

Here is executing result:
img

As we can see, `echo done` is not executed.

## But......Additional note
when external command runs inot failed, the relative output can be **too verbose**, I'm **not sure** if this is ok:
img

# Tests

Make sure you've done the following:

- [X] Add tests that cover your changes, either in the command examples, the crate/tests folder, or in the /tests folder.
- [X] Try to think about corner cases and various ways how your changes could break. Cover them with tests.
- [X] If adding tests is not possible, please document in the PR body a minimal example with steps on how to reproduce so one can verify your change works.

Make sure you've run and fixed any issues with these commands:

- [X] `cargo fmt --all -- --check` to check standard code formatting (`cargo fmt --all` applies these changes)
- [X] `cargo clippy --workspace --features=extra -- -D warnings -D clippy::unwrap_used -A clippy::needless_collect` to check that you're using the standard code style
- [X] `cargo test --workspace --features=extra` to check that all the tests pass

### CODE REVIEW

**Comment by WindSoilder** [comment]
> I think for externals nu shouldn't show an error

Agreed, sorry for that I don't have ideas to achieve it, any ideas?  

I found that if `eval` returns `Err(ShellError)`, then the error message will be shown by `nu`

**Comment by jntrnr** [comment]
for the "2nd part, output by nushell" I don't think we can print an exit code error message unless the user says they want it. Sometimes apps (like `git`) will output non-zero exit codes.

I wrote about this a bit: https://www.jntrnr.com/exit-codes/

**Comment by WindSoilder** [comment]
Ok here is the new result:
img

To make it works properly, I have to change `eval_expression_with_input`'s prototype, so caller can know about external command failed.

**Comment by fdncred** [comment]
> It's not captured in latest main

Thanks for checking. That seems like a bug in another place.

Mac must be a little different because I get a different exit code.
```console
> ^ls adfadf | complete 
ls: cannot access 'adfadf': No such file or directory
╭───────────┬───╮
│ stdout    │   │
│ stderr    │   │
│ exit_code │ 2 │
╰───────────┴───╯
```
maybe the only way to capture stderr right now is with `do`?
```console
> do -i { ^ls adsfd | complete } 
╭───────────┬──────────────────────────────────────────────────────╮
│ stdout    │                                                      │
│ stderr    │ ls: cannot access 'adsfd': No such file or directory │
│           │                                                      │
│ exit_code │ 2                                                    │
╰───────────┴──────────────────────────────────────────────────────╯
```
